<?php
/**
 * Created by PhpStorm.
 * User: wrh42
 * Date: 2018/4/12
 * Time: 1:59
 */

namespace app\index\controller;

class Base extends \app\common\controller\Base {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub



        $this->goMobile();
    }

    protected function goMobile() {
        $mobileAuto = $this->site_config['cfg_mobile_auto'];
        if ($mobileAuto == 1) {
            $wap2web = input('wap2web', 0, 'intval');//手机访问电脑版
            $agent = $_SERVER['HTTP_USER_AGENT'];
            if ($wap2web != 1) {
                if(strpos($agent,"comFront") || strpos($agent,"iPhone") || strpos($agent,"MIDP-2.0") || strpos($agent,"Opera Mini") || strpos($agent,"UCWEB") || strpos($agent,"Android") || strpos($agent,"Windows CE") || strpos($agent,"SymbianOS"))
                {
                    header('Location: /mobile');
                    exit;
                }
            }
        }
    }

    protected function assignAnnounce() {
        $announce_list = model("")->select;
    }

}