<?php
/**
 * Created by PhpStorm.
 * User: wrh42
 * Date: 2018/4/11
 * Time: 16:56
 */

namespace app\admin\controller;

class Base extends \app\common\controller\Base {

    protected $operator = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if( !$this->checkLogin() ) {
            $this->error("请先登录");
        }
        $this->assign("action_name", request()->action());
        $this->assign("operator", $this->operator);
    }

    protected function checkLogin() {
        if( !session('hkwcd_admin_operator') ) {
            return false;
        } else {
            $this->operator = session('hkwcd_admin_operator');
            return true;
        }
    }

}