<?php
/**
 * Created by PhpStorm.
 * User: wrh42
 * Date: 2018/4/11
 * Time: 17:44
 */

namespace app\admin\controller;

use app\admin\model\Category;

class Page extends Base {

    public $category_model = "";
    public $attachment_index_model = "";
    public $attachment_model = "";

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->category_model = $this->lang == "zh-cn" ? "ZhCategory" : "EnCategory";
        $this->attachment_index_model = $this->lang == "zh-cn" ? "ZhAttachmentIndex" : "EnAttachmentIndex";
        $this->attachment_model = $this->lang == "zh-cn" ? "ZhAttachment" : "EnAttachment";
    }

    public function index() {
        $pid = input('pid', 0, 'intval');

        $vo = model($this->category_model)->find($pid);//直接是编辑
        $vo['content'] = htmlspecialchars($vo['content']);//ueditor

        $this->assign("pid", $pid);
        $this->assign("vo", $vo);

        $cate = model($this->category_model)->getCategory();//全部分类
//        var_dump($cate);exit;

        $poscate = Category::getParents($cate, $pid);
        $subcate = Category::getChildren($cate, $pid);


        $this->assign("subcate", $subcate);
        $this->assign("poscate", $poscate);

        return $this->fetch();
    }

    public function indexHandle() {
        $id = input('pid', 0, 'intval');
        $pid = input('pid', 0, 'intval');
        $content = input('content', '', 'trim');
        $description = input('description', '');

        if (!$pid) {
            $this->error('参数错误');
        }


        if (empty($description)) {
            $description = str2sub(strip_tags($content), 200);
        }

        $data = array('id' => $pid, 'description' => $description, 'content' => $content);

        //获取属于分类信息,得到modelid
        $selfCate = Category::getSelf(model($this->category_model)->getCategory(0), $id);//当前栏目信息
        $modelid = $selfCate['modelid'];

        if (false !== model($this->category_model)->isUpdate(true)->save($data)) {

            model($this->attachment_index_model)->where(array('arcid' => $id, 'modelid' => $modelid))->delete();
            //内容中的图片
            $img_arr = array();
            $reg = "/<img[^>]*src=\"((.+)\/(.+)\.(jpg|gif|bmp|png))\"/isU";
            preg_match_all($reg, $content, $img_arr, PREG_PATTERN_ORDER);
            // 匹配出来的不重复图片
            $img_arr = array_unique($img_arr[1]);
            if (!empty($img_arr)) {
                $attid = model($this->attachment_model)
                    ->where(array('filepath' => array('in', $img_arr)))
                    ->field('id')
                    ->select();
                $dataAtt = array();
                if ($attid) {
                    foreach ($attid as $v) {
                        $dataAtt[] = array('attid' => $v["id"],'arcid' => $id, 'modelid' => $modelid);
                    }
                    model($this->attachment_index_model)->saveAll($dataAtt);
                }
            }
            $this->success('修改成功', "/admin/page/index?pid={$pid}&lang={$this->lang}");
        }else {

            $this->error('修改失败');
        }
    }
}